Course:
  GetActive: |
    SELECT materia_id subject_id, MIN(c.curso_de) name
    FROM curso c
    WHERE
      c.curso_dt_ini <= CURRENT_DATE AND
      c.curso_dt_end > CURRENT_DATE
    GROUP BY subject_id
    ORDER BY name
  GetById: |
    SELECT c.curso_dt_ini, c.curso_dt_end, c.curso_de, s.seccion_de
    FROM curso c
    INNER JOIN seccion s ON c.seccion_id = s.seccion_id
    WHERE c.curso_id = @curso_id
  DeleteById: |
    DELETE 
    FROM curso 
    WHERE curso_id = @curso_id
  UpdateDates: |
    UPDATE curso
    SET curso_dt_ini = @curso_dt_ini,
        curso_dt_end = @curso_dt_end
    WHERE curso_id = @curso_id
  GetBySubjectAndSection: |
    SELECT curso_id
    FROM curso
    WHERE
      materia_id = @subject_id AND
      seccion_id = @section_id AND
      curso_dt_ini <= CURRENT_DATE AND
      curso_dt_end > CURRENT_DATE
    LIMIT 1

Section:
  GetByCourse: |
    SELECT s.seccion_id section_id, s.seccion_de name
    FROM seccion s
    INNER JOIN curso c ON s.seccion_id = c.seccion_id
    WHERE c.materia_id = @subject_id
    ORDER BY name
  GetById: |
    SELECT seccion_id, seccion_de 
    FROM seccion 
    WHERE seccion_id = @seccion_id
  DeleteById: |
    DELETE 
    FROM seccion 
    WHERE seccion_id = @seccion_id
  UpdateById: |
    UPDATE seccion
    SET seccion_de = @seccion_de
    WHERE seccion_id = @seccion_id
  GetAll: |
    SELECT seccion_id, seccion_de name
    FROM Seccion
    ORDER BY seccion_de

Student:
  GetByCourseSection: |
    SELECT p.persona_nom name, p.persona_ci ci, AVG(cal.calificacion_am) grade
    FROM curso cur
    INNER JOIN inscripcion i ON cur.curso_id = i.curso_id
    INNER JOIN persona p ON i.alumno_ci = p.persona_ci
    INNER JOIN calificacion cal ON i.inscripcion_id = cal.inscripcion_id
    WHERE
      cur.materia_id = @subject_id AND
      cur.seccion_id = @section_id
    GROUP BY name, ci
    ORDER BY name
  GetAllStudents: |
    SELECT persona_ci, persona_nom name, persona_ci IdNumber
    FROM Persona
    WHERE tipo_persona_id = 2
    ORDER BY persona_nom

Grade:
  Add: |
     WITH curso_info AS (
       SELECT curso_id FROM curso
       WHERE
       materia_id = @subject_id AND
       seccion_id = @section_id
       LIMIT 1
     ),
     inscripcion_info AS (
       SELECT i.inscripcion_id 
       FROM inscripcion i
       JOIN curso_info c ON i.curso_id = c.curso_id
       WHERE i.alumno_ci = @student_ci
       LIMIT 1
     )
     INSERT INTO calificacion (inscripcion_id, calificacion_am)
     SELECT i.inscripcion_id, @grade
     FROM inscripcion_info i

Inscription:
  Add: |
    INSERT INTO Inscripcion (curso_id, alumno_ci, inscripcion_dt)
    VALUES (@curso_id, @alumno_ci, @inscripcion_dt)
  CheckExisting: |
    SELECT inscripcion_id
    FROM Inscripcion
    WHERE alumno_ci = @alumno_ci AND curso_id = @curso_id
    LIMIT 1

Subject:
  GetAll: |
    SELECT materia_id, materia_de name
    FROM Materia
    ORDER BY materia_de

AddPerson:
  InsertPerson: |
    INSERT INTO persona (persona_ci, tipo_persona_id, persona_nom)
    VALUES (@ci, @person_type_id, @name)

Person:
  GetByName: |
    SELECT p.persona_ci, p.persona_nom, t.tipo_persona_de
    FROM persona p
    INNER JOIN tipo_persona t ON p.tipo_persona_id = t.tipo_persona_id
    WHERE p.persona_ci = @person_ci
  DeleteByCI: |
    DELETE 
    FROM persona 
    WHERE persona_ci = @person_ci
  UpdateName: |
    UPDATE persona
    SET persona_nom = @persona_nom
    WHERE persona_ci = @persona_ci

Subject:
  GetById: |
    SELECT materia_id, materia_de 
    FROM materia 
    WHERE materia_id = @materia_id
  DeleteById: |
    DELETE 
    FROM materia 
    WHERE materia_id = @materia_id
  UpdateById: |
    UPDATE materia 
    SET materia_de = @materia_de 
    WHERE materia_id = @materia_id

