Course:
  GetActive: |
    SELECT materia_id subject_id, MIN(c.curso_de) name
    FROM curso c
    WHERE
      c.curso_dt_ini <= CURRENT_DATE AND
      c.curso_dt_end > CURRENT_DATE
    GROUP BY subject_id
    ORDER BY name
  GetBySubjectAndSection: |
    SELECT curso_id
    FROM curso
    WHERE
      materia_id = @subject_id AND
      seccion_id = @section_id AND
      curso_dt_ini <= CURRENT_DATE AND
      curso_dt_end > CURRENT_DATE
    LIMIT 1

Section:
  GetByCourse: |
    SELECT s.seccion_id section_id, s.seccion_de name
    FROM seccion s
    INNER JOIN curso c ON s.seccion_id = c.seccion_id
    WHERE c.materia_id = @subject_id
    ORDER BY name
  GetAll: |
    SELECT seccion_id, seccion_de name
    FROM Seccion
    ORDER BY seccion_de

Student:
  GetByCourseSection: |
    SELECT p.persona_nom name, p.persona_ci ci, AVG(cal.calificacion_am) grade
    FROM curso cur
    INNER JOIN inscripcion i ON cur.curso_id = i.curso_id
    INNER JOIN persona p ON i.alumno_ci = p.persona_ci
    INNER JOIN calificacion cal ON i.inscripcion_id = cal.inscripcion_id
    WHERE
      cur.materia_id = @subject_id AND
      cur.seccion_id = @section_id
    GROUP BY name, ci
    ORDER BY name
  GetAllStudents: |
    SELECT persona_ci, persona_nom name, persona_ci IdNumber
    FROM Persona
    WHERE tipo_persona_id = 2
    ORDER BY persona_nom

Grade:
  Add: |
     WITH curso_info AS (
       SELECT curso_id FROM curso
       WHERE
       materia_id = @subject_id AND
       seccion_id = @section_id
       LIMIT 1
     ),
     inscripcion_info AS (
       SELECT i.inscripcion_id 
       FROM inscripcion i
       JOIN curso_info c ON i.curso_id = c.curso_id
       WHERE i.alumno_ci = @student_ci
       LIMIT 1
     )
     INSERT INTO calificacion (inscripcion_id, calificacion_am)
     SELECT i.inscripcion_id, @grade
     FROM inscripcion_info i

Inscription:
  Add: |
    INSERT INTO Inscripcion (curso_id, alumno_ci, inscripcion_dt)
    VALUES (@curso_id, @alumno_ci, @inscripcion_dt)
  CheckExisting: |
    SELECT inscripcion_id
    FROM Inscripcion
    WHERE alumno_ci = @alumno_ci AND curso_id = @curso_id
    LIMIT 1

Subject:
  GetAll: |
    SELECT materia_id, materia_de name
    FROM Materia
    ORDER BY materia_de