GradeSheet:
  GetActiveCourses: |
    SELECT materia_id subject_id, MIN(c.curso_de) name
    FROM curso c
    WHERE
      c.curso_dt_ini <= CURRENT_DATE AND
      c.curso_dt_end > CURRENT_DATE
    GROUP BY materia_id
    ORDER BY name

  GetCourseSections: |
    SELECT s.seccion_id section_id, s.seccion_de name
    FROM seccion s
    INNER JOIN curso c ON s.seccion_id = c.seccion_id
    WHERE c.materia_id = @materia_id
    ORDER BY name

  GetCourseStudents: |
    SELECT p.persona_nom name, p.persona_ci ci, AVG(cal.calificacion_am) grade
    FROM curso cur
    INNER JOIN inscripcion i ON cur.curso_id = i.curso_id
    INNER JOIN persona p ON i.alumno_ci = p.persona_ci
    INNER JOIN calificacion cal ON i.inscripcion_id = cal.inscripcion_id
    WHERE
      cur.materia_id = @materia_id AND
      cur.seccion_id = @seccion_id
    GROUP BY name, ci
    ORDER BY name
