[pool]
default-size = 20
max-size = 100
size-increment = 5

[db-postgres]
host = "ep-dawn-block-a8ewlpgq-pooler.eastus2.azure.neon.tech"
port = "5432"
user = "Dev"
password = "npg_hJWMo5js0peg"
name = "aCHADemia"